/* Single source of truth. Consumed by the browser (as globals) and by
   build-routes.js in Node. Do not edit generated pages by hand. */
const MH_ROUTES = [
  {
    slug: 'bara-bhangal-shepherds-trail',
    name: 'Bara Bhangal Shepherds’ Trail',
    category: 'Trekking',
    region: 'Himachal',
    diff: 'Challenging',
    heritage: true,
    duration: '12 days',
    alt: '4,878m',
    img: 'Photos/da4e15aa-46b5-4ff6-b1f0-dddf75415c0b.jpg',
    season: 'July to October',
    groupSize: 'Minimum 2, maximum 14 persons',
    highPasses: 'Kalihani and Thamsar Passes',
    overview: 'Also known as the Shepherds\' Trail, this route is reserved for those experienced in rugged backcountry travel and confident with hiking and camping logistics. One of the more demanding treks on offer, it crosses from the lush Kullu valley to the stark landscapes of the Bara Bhangal range — a rewarding route for travellers seeking isolation and immersion in nature.'
  },
  {
    slug: 'hamta-pass-crossing',
    name: 'Hamta Pass Crossing',
    category: 'Trekking',
    region: 'Himachal',
    diff: 'Moderate',
    heritage: true,
    duration: '8 days',
    alt: '4,270m',
    img: 'Photos/94462484-3a39-4c2a-9d94-ccd61cb1b56b.jpg',
    season: 'Monsoon: July to September',
    groupSize: 'Minimum 2, maximum 14 persons',
    highPasses: '',
    overview: 'Starting from Prini village near Manali, this trek crosses the Hamta Pass to the headwaters of the Chandra river in Lahaul, skirting the lower reaches of the Bara Shigri glacier. The approach to the pass offers fine views of Deo Tibba and Indrasan along the way.'
  },
  {
    slug: 'beas-kund-trek',
    name: 'Beas Kund Trek',
    category: 'Trekking',
    region: 'Himachal',
    diff: 'Easy',
    heritage: false,
    duration: '6 days',
    alt: '3,650m',
    img: 'Photos/IMG_1030.jpeg',
    season: 'Monsoon: July to September',
    groupSize: 'Minimum 2, maximum 14 persons',
    highPasses: '',
    overview: 'Starting from Manali, this trek winds through the famous Solang Valley, a hub for winter sports 15 kilometres from town, before continuing via Dhundi and Bakarthach. Along the way are lush meadows, glaciers and snow-capped peaks, ending at the Beas Kund glacier — the birthplace of the River Beas.'
  },
  {
    slug: 'bhrigu-lake-trek',
    name: 'Bhrigu Lake Trek',
    category: 'Trekking',
    region: 'Himachal',
    diff: 'Easy',
    heritage: false,
    duration: '3 days',
    alt: '4,240m',
    img: 'Photos/8bbb4edc-ab6a-42d9-8139-621772ca79cd.jpg',
    season: 'Monsoon: July to September',
    groupSize: 'Minimum 2, maximum 14 persons',
    highPasses: '',
    overview: 'Bhrigu Lake is a prominent glacial lake of the Kullu region, just east of Rohtang Pass. Legend holds that the sage Bhrigu meditated here, and local deities — most notably Guru Vashisht — are said to visit its sacred waters every two or three years. The trek starts at Gulaba, through forests of fir and oak, with steep ups and downs rewarded by breathtaking views.'
  },
  {
    slug: 'malana-trek',
    name: 'Malana Trek',
    category: 'Trekking',
    region: 'Himachal',
    diff: 'Moderate',
    heritage: false,
    duration: '10 days',
    alt: '3,660m',
    img: 'Photos/da4e15aa-46b5-4ff6-b1f0-dddf75415c0b.jpg',
    season: 'May to November',
    groupSize: '',
    highPasses: '',
    overview: 'One of the most enchanting treks in the Kullu valley, combining deep forest, wide hanging valleys and the bleak, moraine-strewn landscape around the Malana glacier. The route ends at Malana, a tribal village considered one of the world\'s oldest democracies, where visitors need the village head\'s permission before entering certain sacred sites.'
  },
  {
    slug: 'kinner-kailash-trek',
    name: 'Kinner Kailash Trek',
    category: 'Trekking',
    region: 'Himachal',
    diff: 'Challenging',
    heritage: false,
    duration: '7 days',
    alt: '5,300m',
    img: 'Photos/94462484-3a39-4c2a-9d94-ccd61cb1b56b.jpg',
    season: 'June to October',
    groupSize: 'Minimum 2, maximum 14 persons',
    highPasses: '',
    overview: 'This trek in Kinnaur completes a circuit around the revered Kinnaur Kailash mountain, on trails only opened to trekkers in recent years and consequently far less used. The Kinnaur Kailash range is dominated by the Kinnaur Kailash (6,349m) and Jorkarden (6,473m) peaks, and the route\'s only pass, the Charang La, sits at 5,300m.'
  },
  {
    slug: 'pin-parvati-trek',
    name: 'Pin Parvati Trek',
    category: 'Trekking',
    region: 'Himachal',
    diff: 'Challenging',
    heritage: false,
    duration: '13 days',
    alt: '5,300m',
    img: 'Photos/IMG_4170.jpeg',
    season: 'July to end of September',
    groupSize: 'Minimum 2, maximum 14 persons',
    highPasses: 'Pin Parvati Pass, Kunzam La and Rohtang Pass',
    overview: 'One of the region\'s most spectacular treks, crossing from the lush Parvati valley in Kullu to the stark, barren Pin valley in Spiti via the high-altitude Mantalai Lake and the Pin Parvati Pass. The route skirts the Pin Valley National Park, known for elusive snow leopards, and the Great Himalayan National Park, home to rare birds such as the Western Tragopan.'
  },
  {
    slug: 'chandertaal-moon-lake-trek',
    name: 'Chandertaal (Moon Lake) Trek',
    category: 'Trekking',
    region: 'Himachal',
    diff: 'Moderate',
    heritage: false,
    duration: '6 days',
    alt: '4,250m',
    img: 'Photos/8bbb4edc-ab6a-42d9-8139-621772ca79cd.jpg',
    season: '15 May to 30 October',
    groupSize: 'Minimum 2, maximum 14 persons',
    highPasses: '',
    overview: 'Chandratal, or \'Moon Lake\', lies in Spiti district between a low ridge and the main Kunzum range, its deep blue water encircled by snow for much of the year. It is the source of the Chandra river, framed by the Mulkila and Chandrabhaga ranges, and local legend holds it as the spot from which Yudhishthira ascended to heaven in his mortal form.'
  },
  {
    slug: 'markha-valley',
    name: 'Markha Valley',
    category: 'Trekking',
    region: 'Ladakh',
    diff: 'Moderate',
    heritage: false,
    duration: '8 days',
    alt: '5,200m',
    img: 'Photos/IMG_3290.jpeg',
    season: 'June to October',
    groupSize: '',
    highPasses: 'Kongmaru La (5,200m), Ganda La (4,900m)',
    overview: 'One of the most popular treks in Ladakh, giving a real feel for the region\'s stark landscape. Its appeal lies in the diversity of terrain — deep gorges and huge canyon walls giving way to high alpine meadows where nomadic shepherds graze goats, sheep and yaks. There are multiple entry points into the valley; this itinerary follows the most popular route.'
  },
  {
    slug: 'zanskar-trek',
    name: 'Zanskar Trek',
    category: 'Trekking',
    region: 'Ladakh',
    diff: 'Challenging',
    heritage: false,
    duration: '10 days',
    alt: '5,060m',
    img: 'Photos/4c862c1f-da63-41ff-add8-1ded0e18edad.jpg',
    season: 'Monsoon: July to September',
    groupSize: '',
    highPasses: '',
    overview: 'For those seeking adventure and untouched natural beauty, this is one of the tougher routes in Ladakh, running from Padum to Lamayuru through barren, remote terrain and over the high Sengge La. It is recommended only for trekkers who are already well acclimatised to altitude before setting out.'
  },
  {
    slug: 'nubra-valley-trek',
    name: 'Nubra Valley Trek',
    category: 'Trekking',
    region: 'Ladakh',
    diff: 'Challenging',
    heritage: false,
    duration: '8 days',
    alt: '5,400m',
    img: 'Photos/IMG_2357.jpeg',
    season: 'June to October',
    groupSize: '',
    highPasses: 'Lasermo La (5,400m)',
    overview: 'The Nubra valley, north of Leh, has a landscape found nowhere else — a desert floor of sand dunes roamed by double-humped Bactrian camels, ringed by peaks of over 6,000m in the Karakoram range. The trek enters via the Lasermo La (5,400m), with fine views over the Indus and Shyok valleys, on ground that was once an important Silk Route stopover.'
  },
  {
    slug: 'lamayuru-trek',
    name: 'Lamayuru Trek',
    category: 'Trekking',
    region: 'Ladakh',
    diff: 'Challenging',
    heritage: false,
    duration: '25 days',
    alt: '5,120m',
    img: 'Photos/IMG_3300.jpeg',
    season: 'May to October',
    groupSize: '',
    highPasses: 'Singe La (5,120m)',
    overview: 'The longest trek in the programme, running 25 days from Delhi and Manali through the Zanskar valley to Lamayuru. The route crosses Shingo La and Singe La, passes the cliff monastery of Phuktal and the villages of Padum, Lingshed and Photoksar, and finishes with a monastery tour around Leh.'
  },
  {
    slug: 'deo-tibba-expedition',
    name: 'Deo Tibba Expedition',
    category: 'Expeditions',
    region: 'Himachal',
    diff: 'Technical',
    heritage: true,
    duration: '14 days',
    alt: '6,001m',
    img: 'Photos/IMG_4170.jpeg',
    season: '15 April to 30 October',
    groupSize: 'Minimum 10 persons per group',
    highPasses: '',
    overview: 'Deo Tibba is a 6,001m peak in the Pir Panjal range near Manali, capped by an extensive icefield. The climb itself is a snow hump, reached once the edge of the ice plateau is gained — a modest technical challenge that rewards climbers with a summit just over the coveted 6,000m mark.'
  },
  {
    slug: 'friendship-peak',
    name: 'Friendship Peak',
    category: 'Expeditions',
    region: 'Himachal',
    diff: 'Technical',
    heritage: false,
    duration: '7 days',
    alt: '5,289m',
    img: 'Photos/8bbb4edc-ab6a-42d9-8139-621772ca79cd.jpg',
    season: 'March to November',
    groupSize: 'Minimum 2, maximum 14 persons',
    highPasses: '',
    overview: 'The Beas Kund glacier, approached from Manali, is one of the region\'s favourite areas for mountaineering and ski touring. Friendship Peak, within it, is an ideal non-technical climb for those with limited or no mountaineering experience, reached from the road head at Solang Nullah.'
  },
  {
    slug: 'kang-yatse-expedition',
    name: 'Kang Yatse Expedition',
    category: 'Expeditions',
    region: 'Ladakh',
    diff: 'Technical',
    heritage: false,
    duration: '14 days',
    alt: '6,200m',
    img: 'Photos/4c862c1f-da63-41ff-add8-1ded0e18edad.jpg',
    season: '1 June to 30 October',
    groupSize: 'Minimum 7 persons per group',
    highPasses: '',
    overview: 'Based in Leh-Ladakh, this climb offers the chance to reach 6,200m without technical climbing skills, or 6,400m with basic technical ability. Challenging yet interesting on its snowy, moderately technical upper slopes, Kang Yatse is often chosen as a climber\'s first Himalayan summit.'
  },
  {
    slug: 'manali-peak-expedition',
    name: 'Manali Peak Expedition',
    category: 'Expeditions',
    region: 'Himachal',
    diff: 'Technical',
    heritage: false,
    duration: '9 days',
    alt: '5,640m',
    img: 'Photos/94462484-3a39-4c2a-9d94-ccd61cb1b56b.jpg',
    season: 'Monsoon: July to September',
    groupSize: 'Minimum 2, maximum 14 persons',
    highPasses: '',
    overview: 'Manali Peak rises in the Pir Panjal range above the Beas valley, its closest village Solang Nala, 13km north of Manali town. At 5,640m it offers a satisfying technical objective, approached via Beas Kund and glacier training before the final fixed-rope and rock-climbing push to the summit.'
  },
  {
    slug: 'ladakhi-peak-expedition',
    name: 'Ladakhi Peak Expedition',
    category: 'Expeditions',
    region: 'Himachal',
    diff: 'Technical',
    heritage: false,
    duration: '11 days',
    alt: '6,000m',
    img: 'Photos/da4e15aa-46b5-4ff6-b1f0-dddf75415c0b.jpg',
    season: '15 April to 30 October',
    groupSize: 'Minimum 10 persons per group',
    highPasses: '',
    overview: 'Starting from Manali, the route to Ladakhi Peak winds through the Solang Valley and on via Dhundi and Bakarthach to the Beas Kund glacier, birthplace of the River Beas. Approached from the same ridge as Shetidhar, the final 50 metres involve a 5.6-grade rock climb, rewarded by panoramic views of the Dhauladhar and Pir Panjal ranges and peaks above 6,000m.'
  },
  {
    slug: 'shetidhar-peak-expedition',
    name: 'Shetidhar Peak Expedition',
    category: 'Expeditions',
    region: 'Himachal',
    diff: 'Technical',
    heritage: false,
    duration: '11 days',
    alt: '5,200m',
    img: 'Photos/IMG_4170.jpeg',
    season: '15 April to 30 October',
    groupSize: 'Minimum 5 persons per group',
    highPasses: '',
    overview: 'Starting from Manali, this climb winds through the Solang Valley, 15km from town, then on via Dhundi and Bakarthach to the Beas Kund glacier, birthplace of the River Beas. From the summit of Shetidhar Peak, climbers are rewarded with a panoramic view across the Dhauladhar and Pir Panjal ranges.'
  },
  {
    slug: 'manali-leh-jeep-safari',
    name: 'Manali–Leh Jeep Safari',
    category: 'Jeep Safari',
    region: 'Himachal–Ladakh',
    diff: 'Easy',
    heritage: false,
    duration: '8 days',
    alt: '5,359m',
    img: 'Photos/IMG_3290.jpeg',
    season: '',
    groupSize: '',
    highPasses: '',
    overview: 'A classic overland route across lofty Himalayan ranges, village life and dramatic scenery, running from Manali to Leh via Rohtang Pass, Sarchu and the high Tibetan plateau at Tanglang La. The best season for the crossing runs from June to mid-October, with camping along the way and monastery visits around Leh.'
  },
  {
    slug: 'lahaul-spiti-jeep-safari',
    name: 'Lahaul–Spiti Jeep Safari',
    category: 'Jeep Safari',
    region: 'Himachal',
    diff: 'Easy',
    heritage: false,
    duration: '13 days',
    alt: '4,558m',
    img: 'Photos/94462484-3a39-4c2a-9d94-ccd61cb1b56b.jpg',
    season: '',
    groupSize: '',
    highPasses: '',
    overview: 'Lahaul is a land of high, uniform mountains and massive glaciers, its Chandra and Bhaga valleys rich in Buddhist art and monastic culture, with ancient murals, thangkas and images of Padmasambhava. Summer brings cool, pleasant weather with green grass and alpine flowers, making July to September the ideal window for this overland route via Keylong and Kaza.'
  },
  {
    slug: 'ladakh-monastery-jeep-safari',
    name: 'Ladakh Monastery Jeep Safari',
    category: 'Jeep Safari',
    region: 'Ladakh',
    diff: 'Easy',
    heritage: false,
    duration: '15 days',
    alt: '3,850m',
    img: 'Photos/4c862c1f-da63-41ff-add8-1ded0e18edad.jpg',
    season: '',
    groupSize: '',
    highPasses: '',
    overview: 'Leh Ladakh\'s monasteries are each known for their own festival, celebrated to mark the founding of the gompa, the birthday of a patron saint, or a major event in Tibetan Buddhist history — with feasting, singing and dancing, mostly in winter but some in summer. This safari visits the region\'s monasteries from Leh through Zanskar to Padum and back.'
  },
  {
    slug: 'ladakh-lakes-jeep-safari',
    name: 'Ladakh Lakes Jeep Safari',
    category: 'Jeep Safari',
    region: 'Ladakh',
    diff: 'Easy',
    heritage: false,
    duration: '10 days',
    alt: '5,606m',
    img: 'Photos/IMG_3290.jpeg',
    season: '',
    groupSize: '',
    highPasses: '',
    overview: 'Ladakh, the land of high passes and gompas: this safari crosses the remote Changthang Plateau to the mesmerising blue waters of Pangong, Tsomoriri and Tso Kar, follows stretches of the ancient Silk Route, and climbs to the highest motorable pass in the world, Khardung La (5,606m).'
  },
  {
    slug: 'nubra-valley-jeep-safari',
    name: 'Nubra Valley Jeep Safari',
    category: 'Jeep Safari',
    region: 'Ladakh',
    diff: 'Easy',
    heritage: false,
    duration: '11 days',
    alt: '5,600m',
    img: 'Photos/IMG_2357.jpeg',
    season: '',
    groupSize: '',
    highPasses: '',
    overview: 'Nubra Valley, north of Leh, is reached via the highest motorable road in the world, Khardung La (5,600m), with views over the Saser Spur, the Zanskar range and the Himalayan chain. The valley itself sits at a milder 3,000m and was once the last staging post for caravan trade with Central Asia.'
  },
  {
    slug: 'trans-himalayan-jeep-safari',
    name: 'Trans-Himalayan Jeep Safari',
    category: 'Jeep Safari',
    region: 'Himachal–Ladakh',
    diff: 'Easy',
    heritage: false,
    duration: '16 days',
    alt: '5,600m',
    img: 'Photos/da4e15aa-46b5-4ff6-b1f0-dddf75415c0b.jpg',
    season: '',
    groupSize: '',
    highPasses: '',
    overview: 'This safari follows the ancient Trans-Himalayan trade route to remote villages and monasteries, from Delhi via Shimla to the Sangla valley in Kinnaur, then into the stark Spiti Valley, with stops at Tabo, Kaza and Dhankar Gompa and the high village of Kibber, before continuing into Ladakh.'
  },
  {
    slug: 'spiti-valley-motorbike-tour',
    name: 'Spiti Valley Motorbike Tour',
    category: 'Mountain Biking',
    region: 'Himachal',
    diff: 'Moderate',
    heritage: false,
    duration: '10 days',
    alt: '4,558m',
    img: 'Photos/IMG_4170.jpeg',
    season: 'Summer: June to October',
    groupSize: 'Minimum 6 people',
    highPasses: '',
    overview: 'A motorbike tour into the Spiti Valley riding through the Banjar Valley and into Kinnaur, with highlights including the striking Bhimakali Temple at Sarahan and the village of Nako, close to the Tibetan border, before crossing into Spiti itself via Kaza and Chandratal Lake.'
  },
  {
    slug: 'manali-leh-ladakh-motorbike-tour',
    name: 'Manali–Leh Ladakh Motorbike Tour',
    category: 'Mountain Biking',
    region: 'Himachal–Ladakh',
    diff: 'Moderate',
    heritage: false,
    duration: '10 days',
    alt: '5,359m',
    img: 'Photos/4c862c1f-da63-41ff-add8-1ded0e18edad.jpg',
    season: 'June to October',
    groupSize: 'Minimum 6 people',
    highPasses: '',
    overview: 'A motorbike tour from Manali, India\'s outdoor sports capital, over the Tanglang La (5,359m) and the world\'s highest motorable pass, Khardung La (5,540m), to the edge of Tibet. Highlights include the ancient Alchi Monastery, the markets of Leh, a camel safari at Hundar in the Nubra Valley and a soak in the Panamik hot springs.'
  },
  {
    slug: 'leh-ladakh-mountain-biking',
    name: 'Leh–Ladakh Mountain Biking',
    category: 'Mountain Biking',
    region: 'Himachal–Ladakh',
    diff: 'Challenging',
    heritage: false,
    duration: '17 days',
    alt: '5,328m',
    img: 'Photos/IMG_3290.jpeg',
    season: 'July to mid-August',
    groupSize: 'Minimum 6 people',
    highPasses: '',
    overview: 'A 490km expedition from Manali to Leh — one of the ultimate rides for an experienced mountain biker. Crossing the Himalayas south to north, the route traverses four of the world\'s highest passes, including Tanglang La at 5,328m, the world\'s second-highest motorable pass, through the isolated Karakoram and Zanskar ranges above the Indus valley.'
  },
  {
    slug: 'spiti-valley-cycling-tour',
    name: 'Spiti Valley Cycling Tour',
    category: 'Mountain Biking',
    region: 'Himachal',
    diff: 'Challenging',
    heritage: false,
    duration: '15 days',
    alt: '4,558m',
    img: 'Photos/8bbb4edc-ab6a-42d9-8139-621772ca79cd.jpg',
    season: 'Summer: June to October',
    groupSize: 'Minimum 6 people',
    highPasses: '',
    overview: 'An 800km cycling expedition from Manali to Shimla through Lahaul and Spiti, the largest district in Himachal Pradesh, bordered by Ladakh, Tibet, Kinnaur and the Kullu valley. One of the toughest routes even for experienced riders, it passes through the former kingdom of Spiti, where colourful Buddhist gompas dominate village life.'
  },
  {
    slug: 'adventure-camp',
    name: 'Adventure Camp',
    category: 'Camps',
    region: 'Himachal',
    diff: 'Easy',
    heritage: false,
    duration: '7 days',
    alt: '3,800m',
    img: 'Photos/94462484-3a39-4c2a-9d94-ccd61cb1b56b.jpg',
    season: 'March to November',
    groupSize: 'Minimum 20 persons',
    highPasses: '',
    overview: 'An adventure camp in the western Himalayas designed to build discipline, coordination and teamwork alongside physical development, combined with exploration of the valley\'s culture, earthquake-resistant architecture and ancient temples. The region is predominantly farming country, known for its apple orchards, with a Hindu majority living alongside a Buddhist minority migrated from Tibet and neighbouring districts.'
  },
  {
    slug: 'trekking-camp',
    name: 'Trekking Camp',
    category: 'Camps',
    region: 'Himachal',
    diff: 'Easy',
    heritage: false,
    duration: '11 days',
    alt: '',
    img: 'Photos/da4e15aa-46b5-4ff6-b1f0-dddf75415c0b.jpg',
    season: '',
    groupSize: '',
    highPasses: '',
    overview: 'An educational programme with a demanding itinerary, designed to test participants\' stamina and willpower through gradual acclimatisation and sustained exposure to the outdoors. Aimed particularly at building children\'s confidence, it fosters leadership, teamwork, negotiation and discipline in a supportive group environment over the course of the camp.'
  },
  {
    slug: 'skill-development-camp',
    name: 'Skill Development Camp',
    category: 'Camps',
    region: 'Himachal',
    diff: 'Easy',
    heritage: false,
    duration: '5–7 days',
    alt: '',
    img: 'Photos/IMG_4170.jpeg',
    season: 'March to November',
    groupSize: 'Minimum 20 persons',
    highPasses: '',
    overview: 'Based at Camp Manali, this outdoor experiential programme helps participants discover life skills, leadership and team spirit away from the comforts of home. Combining rock climbing, river crossing, snow hiking, paragliding and rafting on the Beas, it builds resilience and coping ability that carries over into everyday life.'
  },
  {
    slug: 'spiti-culture-tour',
    name: 'Spiti Culture Tour',
    category: 'Culture Tours',
    region: 'Himachal',
    diff: '',
    heritage: false,
    duration: 'By enquiry',
    alt: '',
    img: 'Photos/8bbb4edc-ab6a-42d9-8139-621772ca79cd.jpg',
    season: '',
    groupSize: '',
    highPasses: '',
    overview: 'Spiti shares its stark landscape and architecture with Ladakh and Zanskar, and is home to a homogeneous Buddhist society of the Mahayana tradition. Its five main monasteries — Tabo, Dhankhar, Kungri, Tangyud and Ki — trace back to the 11th-century pioneer Rinchen Tsangpo, and chortens and mani walls mark the valley throughout, with local festivals offering a window into this living Buddhist culture.'
  },
  {
    slug: 'leh-culture-tour',
    name: 'Leh Culture Tour',
    category: 'Culture Tours',
    region: 'Ladakh',
    diff: '',
    heritage: false,
    duration: 'By enquiry',
    alt: '',
    img: 'Photos/IMG_3290.jpeg',
    season: '',
    groupSize: '',
    highPasses: '',
    overview: 'Ladakh\'s way of life revolves around its many monasteries — Hemis, Spituk, Phyang, Lamayuru, Likir, Alchi, Basgo, Shey and Stakna among the best known — with those near Leh close together and the Zanskar gompas more remote and reached on foot. The tour also includes a day spent with a Ladakhi family, guided by a local, to experience their customs firsthand.'
  },
  {
    slug: 'kullu-culture-tour',
    name: 'Kullu Culture Tour',
    category: 'Culture Tours',
    region: 'Himachal',
    diff: '',
    heritage: false,
    duration: 'By enquiry',
    alt: '',
    img: 'Photos/94462484-3a39-4c2a-9d94-ccd61cb1b56b.jpg',
    season: '',
    groupSize: '',
    highPasses: '',
    overview: 'Known as \'the land of gods\', the Kullu valley\'s fairs, customs and beliefs reflect a way of life lived close to nature. Villages worship local deities — sages, snake gods and figures from ancient scripture — in temples renowned for their carving, and the valley\'s folk arts, dances and songs carry a rich tradition of craftsmanship built up over centuries.'
  }
];

const MH_ITINERARIES = {
  'Bara Bhangal Shepherds’ Trail': [
    { day: 1, title: 'Arrival in Manali', elevation: 2050, desc: 'Participants arrive in Manali.' },
    { day: 2, title: 'Manali to Lama Dugh', elevation: 3017, desc: 'Steep climb through thick forest with no water point after Manali; views of Indrasan, Deo Tibba and the Bara Shigri glacier peaks open up. Camp on an alpine plateau thick with flowers.' },
    { day: 3, title: 'Lama Dugh to Riyali Thach', elevation: 3400, desc: 'A steep ridge below Khand Pari Tibba (4,000m), with views over Manali and the upper Kullu valley.' },
    { day: 4, title: 'Riyali Thach to Base of Kalihani Pass', elevation: 4010, desc: 'Open meadows, a steep descent to a stream crossing, then a steep climb to camp at the base of Kalihani Pass.' },
    { day: 5, title: 'Base of Kalihani to Devi ki Marhi via Kalihani Pass', elevation: 4725, desc: 'A long, arduous day crossing scree, moraine and the Kalihani glacier — 360° views of hanging glaciers, the Pir Panjal and Dhauladhar ranges — then descend past four glacial lakes.' },
    { day: 6, title: 'Devi ki Marhi to Dal Marhi', elevation: 3900, desc: 'Cross the Kalihani Nullah into oak and birch forest, mostly flat with a steep climb near the end.' },
    { day: 7, title: 'Dal Marhi to Bara Bhangal', elevation: 2882, desc: 'Down the Ravi river into deodar forest to the isolated village of Bara Bhangal.' },
    { day: 8, title: 'Rest day at Bara Bhangal', elevation: 2882, desc: 'Explore the village, home to the Gaddi tribe, seldom visited by outsiders.' },
    { day: 9, title: 'Bara Bhangal to Mardh', elevation: 3830, desc: 'Climb through pine, deodar and birch forest toward the Thamsar glacier, base of the next big pass.' },
    { day: 10, title: 'Mardh to Plachak via Thamsar Pass', elevation: 4878, desc: 'Steep ascent over moraine, scree and glacier to Thamsar Pass — the trek\'s highest point — with first views of the lush Kangra valley, then a long descent to Plachak.' },
    { day: 11, title: 'Plachak to Rajgundha', elevation: 2440, desc: 'The easiest day of the trek: flat pine forest walking with views over the open Kangra valley.' },
    { day: 12, title: 'Rajgundha to Billing', elevation: 2310, desc: 'Easy walk through pine forest to Billing, end of the trek — vehicle transfer to Bir or Dharamshala.' }
  ],
  'Beas Kund Trek': [
    { day: 1, title: 'Manali', elevation: 2050, desc: 'Arrival, then Hidimba temple, old Manali and the Vashisht hot-spring village.' },
    { day: 2, title: 'Manali to Solang to Dhundi to Bakarthach', elevation: 3300, desc: 'Drive to Solang Nallah and Dhundi, then walk to Bakarthach — base of the surrounding peaks (Shetidhar, Ladakhi, Friendship, Hanuman Tibba).' },
    { day: 3, title: 'Bakarthach to Beas Kund', elevation: 3650, desc: 'A gradual ascent over moraine to the small glacial lake at Beas Kund, the birthplace of the Beas river.' },
    { day: 4, title: 'Beas Kund', elevation: 3650, desc: 'An easy exploration walk around the lake and back to camp.' },
    { day: 5, title: 'Beas Kund to Manali', elevation: 2050, desc: 'Trek down to Dhundi and drive to Manali.' },
    { day: 6, title: 'Manali — departure', elevation: 2050, desc: 'Transfer for onward journey.' }
  ],
  'Hamta Pass Crossing': [
    { day: 1, title: 'Delhi to Manali', elevation: 1960, desc: 'Overnight train then drive from Anandpur Sahib to Manali.' },
    { day: 2, title: 'Manali to Chika', elevation: 3100, desc: 'Jeep to Jobra, then a gradual 2-hour walk uphill and downhill, crossing streams to the Hampta river.' },
    { day: 3, title: 'Chika to Balu Ghera', elevation: 3700, desc: '3–4 hours of short ups and downs.' },
    { day: 4, title: 'Balu Ghera to Hamta Pass to Shiyagaru', elevation: 4270, desc: 'Cross Hamta Pass and descend into the Chandra valley, with views of Deo Tibba, Indrasan and the Lahaul valleys.' },
    { day: 5, title: 'Shiyagaru to Chatru to Manali', elevation: 1960, desc: 'River crossings and a 3–4 hour descent to Chatru, then drive back to Manali over Rohtang.' }
  ],
  'Markha Valley': [
    { day: 1, title: 'Arrival in Leh', elevation: 3500, desc: 'Participants arrive and rest to acclimatise.' },
    { day: 2, title: 'Leh to Spituk to Zingchen', elevation: 3380, desc: 'Drive to Spituk then a long barren stretch into the lush Zingchen valley where the Rumbak river meets the Indus.' },
    { day: 3, title: 'Zingchen to Base of Ganda La', elevation: 3900, desc: 'Enter Hemis National Park — look out for snow leopard and blue sheep — climb past a couple of villages.' },
    { day: 4, title: 'Base of Ganda La to Skiu via Ganda La', elevation: 4900, desc: 'Ascend to Ganda La, then a gradual descent and easy walk to camp at Skiu.' },
    { day: 5, title: 'Skiu to Markha', elevation: 3300, desc: 'Easy walk along the Markha river, crossing it several times, to the valley\'s largest village.' },
    { day: 6, title: 'Markha to Thachungtse', elevation: 3800, desc: 'Past old stone mills, mani walls, a castle and a monastery, then out toward Thachungtse.' },
    { day: 7, title: 'Thachungtse to Nimaling', elevation: 4878, desc: 'The easiest day — a gradual ascent over the open meadows of Nimaling.' },
    { day: 8, title: 'Nimaling to Shang Sumdo via Kongmaru La', elevation: 5200, desc: 'Cross the trek\'s highest pass, then a steep descent leveling out into the Shang gorge to Shang Sumdo, where a vehicle meets you for Leh.' }
  ],
  'Deo Tibba Expedition': [
    { day: 1, title: 'Delhi to Manali', elevation: 2050, desc: 'Arrive in Manali, check in and rest. Gear preparation.' },
    { day: 2, title: 'Manali — acclimatisation', elevation: 2050, desc: 'Visit the Hadimba temple and the Vashisht hot springs while double-checking expedition gear.' },
    { day: 3, title: 'Manali to Chikka', elevation: 3350, desc: 'Drive 12km to the tunnel point, then trek 3km to the green camp at Chikka.' },
    { day: 4, title: 'Chikka to Seri', elevation: 3800, desc: 'An 8km gradual climb up the valley floor to the wide, flat meadow at Seri.' },
    { day: 5, title: 'Seri to Chandertaal — Deo Tibba base', elevation: 4480, desc: 'Trek over moraine to the small high-altitude lake of Chandertaal at the foot of Deo Tibba — the source of the Duhangan river.' },
    { day: 6, title: 'Deo Tibba base — glacier training', elevation: 4480, desc: 'Move onto the Deo Tibba glacier to practise ascending and descending technique on snow and ice.' },
    { day: 7, title: 'Deo Tibba base — training and prep', elevation: 4480, desc: 'A second day of technique on the glacier, followed by evening preparation and briefing for the climb.' },
    { day: 8, title: 'Base camp to Camp 1', elevation: 5200, desc: 'A gradual ascent to Camp 1, finishing with roughly 120m of fixed-rope climbing. Early dinner, overnight in tents.' },
    { day: 9, title: 'Summit day — Deo Tibba', elevation: 6001, desc: 'A 2am start: gradual climbing, then a 150m gully on fixed rope, more gradual ground, and a final 50m fixed-rope section to the summit. Descend safely to Camp 1.' },
    { day: 10, title: 'Camp 1 to base camp', elevation: 4480, desc: 'Descend to base camp; the rest of the day is free.' },
    { day: 11, title: 'Weather buffer day', elevation: 4480, desc: 'A spare day held in reserve for bad weather.' },
    { day: 12, title: 'Base camp to Chikka', elevation: 3350, desc: 'Descend the valley back to Chikka.' },
    { day: 13, title: 'Chikka to Manali', elevation: 2050, desc: 'An easy trek to the tunnel point, then the drive down to Manali.' },
    { day: 14, title: 'Manali to Delhi', elevation: 216, desc: 'Time in Manali town, then the evening departure for Delhi.' }
  ],
  'Friendship Peak': [
    { day: 1, title: 'Arrival in Manali', elevation: 2050, desc: 'Arrive and rest.' },
    { day: 2, title: 'Manali to Solang to Dhundi to Bakarthach', elevation: 3300, desc: 'Drive to Solang Nallah, hub of local adventure activities, then jeep to Dhundi and on to Bakarthach.' },
    { day: 3, title: 'Glacier training at Beas Kund', elevation: 3600, desc: 'Practice ascending and descending on snow and ice, dry-fruit distribution and prep for the days ahead.' },
    { day: 4, title: 'Steep ascent to Camp 1', elevation: 4500, desc: 'Pack-lunch day establishing Camp 1, with an acclimatisation walk after evening tea.' },
    { day: 5, title: 'Rest and acclimatisation day', elevation: 4500, desc: 'Rest at Camp 1.' },
    { day: 6, title: 'Summit day — Friendship Peak', elevation: 5289, desc: 'Start around 2am, roped climbing to the summit (~6 hours) — panoramic views of the Dhauladhar and Pir Panjal ranges, Indrasan and Deo Tibba — then back to Camp 1.' },
    { day: 7, title: 'Camp 1 to Dhundi to Manali', elevation: 2050, desc: 'Descend to Dhundi and drive back to Manali.' }
  ],
  'Kang Yatse Expedition': [
    { day: 1, title: 'Leh to Zinchen', elevation: 3400, desc: 'Transfer to Spituk to meet the team, then hike west along the Indus into Hemis National Park to Zinchen.' },
    { day: 2, title: 'Zinchen to base of Ganda La', elevation: 4500, desc: 'Down the gorge, multiple river crossings, ascend toward the foot of Ganda La.' },
    { day: 3, title: 'Yurutse to Skiu via Ganda La', elevation: 4800, desc: 'Cross Ganda La then descend into the Markha valley to camp at Skiu.' },
    { day: 4, title: 'Skiu to Markha', elevation: 3710, desc: 'Several river crossings along the Markha valley to the village of Markha.' },
    { day: 5, title: 'Markha to Tchatchutse', elevation: 3750, desc: 'Past the monastery of Humlung near Hankar, up a narrower valley to Tchatchutse.' },
    { day: 6, title: 'Tchatchutse to base of Kang Yatse', elevation: 5040, desc: 'Past yak pastures to base camp, with an evening acclimatisation walk to 5,400m.' },
    { day: 7, title: 'Summit day — Kang Yatse to Nimaling', elevation: 6200, desc: 'Start around 2am; 5–7 hours to the summit on snowy, moderately technical slopes, then descend to Nimaling.' },
    { day: 8, title: 'Security day at Nimaling', elevation: 4878, desc: 'Weather buffer day; walk among the high-altitude shepherd pastures if conditions allow.' },
    { day: 9, title: 'Nimaling to Shang via Kongmaru La', elevation: 5150, desc: 'Cross the magnificent river bed and a difficult slope to Shang.' },
    { day: 10, title: 'Shang to Leh', elevation: 3500, desc: 'Drive back to Leh.' }
  ],
  'Pin Parvati Trek': [
    { day: 1, title: 'Arrive Bhuntar to Manikaran', elevation: 1760, desc: 'Vehicle transfer to Manikaran.' },
    { day: 2, title: 'Manikaran to Barsheni to Khirganga', elevation: 3020, desc: 'A hot spring where Lord Shiva is said to have meditated.' },
    { day: 3, title: 'Khirganga to Tunda Bhuj', elevation: 3285, desc: 'Dense forest and flower-strewn meadows, a steep gradual climb.' },
    { day: 4, title: 'Tunda Bhuj to Thakur Kuan', elevation: 3620, desc: 'Waterfalls, lakes and meadows.' },
    { day: 5, title: 'Thakur Kuan to Odi Thach', elevation: 3800, desc: 'Cross the Pandu Bridge, a single-rock span said to be built by the Pandavas in exile.' },
    { day: 6, title: 'Odi Thach to Mantalai Lake', elevation: 4115, desc: 'Gradual climb to the source lake of the Parvati river, beneath the Mantalai Glacier.' },
    { day: 7, title: 'Mantalai to base of Pin Parvati Pass', elevation: 4300, desc: 'Ascend to the base camp of Mount Parvati, also the base of the pass.' },
    { day: 8, title: 'Base of Pin Pass over the pass', elevation: 5300, desc: 'A steep climb over Pin Parvati Pass — views of the Hamta region on one side, the Pin valley of Spiti on the other.' },
    { day: 9, title: 'Campsite over Pin Pass to Tiai', elevation: 3700, desc: 'Along the Pin river into Pin Valley National Park — snow leopard, musk deer and ibex country.' },
    { day: 10, title: 'Tiai to Mud', elevation: 3650, desc: 'Through the stark landscape of Spiti to the village of Mud.' },
    { day: 11, title: 'Mud to Gulling to Kaza', elevation: 3650, desc: 'Rough-road walk with views of Spiti\'s "middle country", then jeep transfer to Kaza.' },
    { day: 12, title: 'Monastic sightseeing around Kaza', elevation: 3650, desc: 'Ki monastery, Kibber village, Dhankar and Tabo monasteries.' },
    { day: 13, title: 'Kaza to Manali', elevation: 2050, desc: 'Drive via Kunzum Pass, Keylong, Koksar and Rohtang Pass back to Manali.' }
  ],
  'Zanskar Trek': [
    { day: 1, title: 'Padum to Karsha / Rinum', elevation: 3600, desc: 'Visit Karsha, the largest and most important monastery in Zanskar, built in the 15th century.' },
    { day: 2, title: 'Karsha to Pishu', elevation: 3400, desc: 'Easy trail mostly following the Zanskar River, with a detour to the longest hanging bridge over it.' },
    { day: 3, title: 'Pishu to Hanumil', elevation: 3550, desc: 'Left-bank trail, a moraine or two to cross.' },
    { day: 4, title: 'Hanumil to Snertse', elevation: 4200, desc: 'Away from the river, up to the plateau and the foot of Parfi La.' },
    { day: 5, title: 'Snertse to Lingshed', elevation: 3800, desc: 'Ascent to Hanuma La pass through gorges past a sheep fold.' },
    { day: 6, title: 'Lingshed to base of Sengge La', elevation: 5060, desc: 'Via Margum La and Kuba La to the base of Sengge La.' },
    { day: 7, title: 'Sengge La to Photoksar', elevation: 3750, desc: 'Climb to Boumitse La then descend to Photoksar.' },
    { day: 8, title: 'Photoksar to Hanupatta', elevation: 3500, desc: 'A long ascent to Sirsir La.' },
    { day: 9, title: 'Hanupatta to Wanla', elevation: 3300, desc: 'Continue across the slope into the gorge.' },
    { day: 10, title: 'Wanla to Lamayuru', elevation: 3510, desc: 'Along the Shill Kong, through Shilla village and a dry gorge to Lamayuru.' }
  ],
  'Manali–Leh Jeep Safari': [
    { day: 1, title: 'Delhi arrival', elevation: 216, desc: 'Transfer to hotel, overnight stay.' },
    { day: 2, title: 'Delhi to Manali', elevation: 2050, desc: 'Evening drive by AC coach, overnight journey.' },
    { day: 3, title: 'Manali', elevation: 2050, desc: 'Acclimatise, visit Hadimba Devi Temple, explore the mall road.' },
    { day: 4, title: 'Manali to Sarchu', elevation: 4290, desc: 'Via Rohtang Pass and Keylong; deluxe tent camp at Sarchu.' },
    { day: 5, title: 'Sarchu to Leh', elevation: 3500, desc: 'Over Tanglang La (5,359m) via the Moore Plains, the high Tibetan Plateau.' },
    { day: 6, title: 'Leh — Shey, Thiksey, Hemis', elevation: 3500, desc: 'Sightseeing at three of Ladakh\'s most important monasteries.' },
    { day: 7, title: 'Leh — Khardung La', elevation: 5600, desc: 'The highest motorable road in the world; views over the Indus valley and the Zanskar range.' },
    { day: 8, title: 'Leh to Delhi', elevation: 216, desc: 'Flight to Delhi, international transfer.' }
  ],
  'Malana Trek': [
    { day: 1, title: 'Arrival in Delhi', elevation: 216, desc: 'Reception at the airport, transfer to hotel.' },
    { day: 2, title: 'Delhi to Manali', elevation: 2000, desc: 'Overnight tourist bus, 570km.' },
    { day: 3, title: 'Manali', elevation: 2000, desc: 'Old Manali, Hadimba temple, Shiva temple and town monastery.' },
    { day: 4, title: 'Manali to Rumsu', elevation: 2135, desc: 'Drive to Nagar, explore the castle and Roerich gallery, then climb to the traditional village of Rumsu.' },
    { day: 5, title: 'Rumsu to Chiklani', elevation: 2378, desc: 'A steady climb to base camp through oak, poplar, pine and rhododendron.' },
    { day: 6, title: 'Chiklani to Nagruni via Chandrakhani Pass', elevation: 3660, desc: 'A short climb to the pass gives extensive views of the snow-capped ranges and the Kullu valley, then an easy forest walk to camp.' },
    { day: 7, title: 'Nagruni to Malana', elevation: 2652, desc: 'Descend to Malana — a village of distinct dialect and customs, considered one of the world\'s oldest democracies.' },
    { day: 8, title: 'Malana to Manali via Manikaran', elevation: 2000, desc: 'Descend to the road head and visit the Manikaran hot-spring pilgrimage site.' },
    { day: 9, title: 'Manali to Delhi', elevation: 216, desc: 'Overnight bus.' },
    { day: 10, title: 'Arrive Delhi', elevation: 216, desc: 'Half-day sightseeing, then onward flight.' }
  ],
  'Bhrigu Lake Trek': [
    { day: 1, title: 'Manali to Gulaba to Kothi Theli', elevation: 2900, desc: 'Drive up the Rohtang highway to Gulaba, then climb through dense deodar forest to camp.' },
    { day: 2, title: 'Kothi Theli to Bhrigu Lake and back', elevation: 4240, desc: 'Ascend slowly to the sacred glacial lake, spend time there, then return to camp.' },
    { day: 3, title: 'Kothi Theli to Manali', elevation: 2050, desc: 'Walk back to Gulaba and drive down to Manali.' }
  ],
  'Kinner Kailash Trek': [
    { day: 1, title: 'Arrival in Shimla', elevation: 2200, desc: 'Arrive and rest.' },
    { day: 2, title: 'Shimla to Sangla to Thangi', elevation: 2760, desc: 'A long drive via the district town of Recong Peo.' },
    { day: 3, title: 'Thangi to Lambar', elevation: 2890, desc: 'Alpine scenery, part of the trail passing through a grand gorge.' },
    { day: 4, title: 'Lambar to Charang', elevation: 3500, desc: 'A continued ascent to the large village named after the nearby pass.' },
    { day: 5, title: 'Charang to Lalanti', elevation: 4420, desc: 'To the shepherds\' meadow campsite at the base of Charang La.' },
    { day: 6, title: 'Lalanti to Chitkul via Charang La', elevation: 5300, desc: 'A demanding climb with spectacular views from the pass, then a steep descent to the warm camp at Chitkul.' },
    { day: 7, title: 'Chitkul to Shimla', elevation: 2200, desc: 'Drive back to Shimla.' }
  ],
  'Chandertaal (Moon Lake) Trek': [
    { day: 1, title: 'Manali', elevation: 2050, desc: 'Hadimba Devi temple, old Manali and the mall road.' },
    { day: 2, title: 'Manali to Rohtang Pass to Dadarpul', elevation: 3250, desc: 'Drive over Rohtang, gateway to Lahaul-Spiti, and on to camp at Dadarpul.' },
    { day: 3, title: 'Dadarpul to Kunzum Pass to Moon Lake', elevation: 4250, desc: 'Drive to Kunzum Pass, then trek to the deep-blue crescent lake with panoramic CB-range views.' },
    { day: 4, title: 'Rest day at Moon Lake', elevation: 4250, desc: 'A leisure day by the lake.' },
    { day: 5, title: 'Moon Lake to Manali', elevation: 2050, desc: 'The long drive back to Manali.' },
    { day: 6, title: 'Manali', elevation: 2050, desc: 'Free day, evening departure.' }
  ],
  'Nubra Valley Trek': [
    { day: 1, title: 'Arrive in Leh', elevation: 3500, desc: 'Arrive and rest to acclimatise.' },
    { day: 2, title: 'Leh to Phyang to Phyang Phu', elevation: 3700, desc: 'Drive to the ancient Phyang monastery, then a short walk to Phyang Phu.' },
    { day: 3, title: 'Phyang Phu to South base of Lasermo La', elevation: 4700, desc: 'A gradual climb through high-altitude wildlife country.' },
    { day: 4, title: 'South base to North base via Lasermo La', elevation: 5400, desc: 'An early start over the pass, then a descent through glacier and moraine to a meadow camp.' },
    { day: 5, title: 'North base to Hunder Dok', elevation: 4000, desc: 'An easy meadow walk along the Hunder stream.' },
    { day: 6, title: 'Hunder Dok to Skarchen', elevation: 3800, desc: 'Past the Nubra villages of Dok Gongma, Dok Yongma and Wachan.' },
    { day: 7, title: 'Skarchen to Hunder', elevation: 3100, desc: 'Through a gorge that opens dramatically into the Shyok valley.' },
    { day: 8, title: 'Hunder to Leh', elevation: 3500, desc: 'Drive back to Leh.' }
  ],
  'Lamayuru Trek': [
    { day: 1, title: 'Arrival in Delhi', elevation: 216, desc: 'Arrive and rest.' },
    { day: 2, title: 'Delhi to Manali', elevation: 2000, desc: 'Overnight tourist bus, 570km.' },
    { day: 3, title: 'Manali', elevation: 2000, desc: 'Rest and acclimatise.' },
    { day: 4, title: 'Manali to Darcha-Palamo', elevation: 3600, desc: '150km drive into Lahaul.' },
    { day: 5, title: 'Palamo to Zanskar Sumdo', elevation: 3950, desc: 'The trek begins.' },
    { day: 6, title: 'Zanskar Sumdo to Chhumik Marpo', elevation: 4500, desc: 'A long day up the valley.' },
    { day: 7, title: 'Chhumik Marpo to Lakhang via Shingo La', elevation: 5090, desc: 'Cross the Shingo La into Zanskar.' },
    { day: 8, title: 'Lakhang to Kargyak', elevation: 4060, desc: 'Descend to the village of Kargyak.' },
    { day: 9, title: 'Kargyak to Purni', elevation: 3800, desc: 'Follow the Kargyak river.' },
    { day: 10, title: 'Purni to Phuktal and back', elevation: 3800, desc: 'Visit the spectacular cliff monastery of Phuktal.' },
    { day: 11, title: 'Purni to Pipula', elevation: 3600, desc: 'Continue down the valley.' },
    { day: 12, title: 'Pipula to Raru via Ichar', elevation: 3700, desc: 'Riverside trail.' },
    { day: 13, title: 'Raru to Padum', elevation: 3600, desc: 'To the capital of Zanskar.' },
    { day: 14, title: 'Padum to Rinam', elevation: 3500, desc: 'Along the Zanskar river.' },
    { day: 15, title: 'Rinam to Pishu via Jangla', elevation: 3400, desc: 'A long river-valley day.' },
    { day: 16, title: 'Pishu to Hanumil', elevation: 3550, desc: 'Follow the Zanskar.' },
    { day: 17, title: 'Hanumil to Snertse via Parfi La', elevation: 4200, desc: 'Up to the plateau over Parfi La.' },
    { day: 18, title: 'Snertse to Lingshed via Hanuma La', elevation: 4700, desc: 'Through gorges over Hanuma La.' },
    { day: 19, title: 'Lingshed to Yulchung Gyra via Murgum La', elevation: 4500, desc: 'Cross Murgum La.' },
    { day: 20, title: 'Yulchung Gyra to Photoksar via Sengge La', elevation: 5120, desc: 'The high pass of the trek.' },
    { day: 21, title: 'Photoksar to Hanupata via Sirsir La', elevation: 4815, desc: 'Over Sirsir La.' },
    { day: 22, title: 'Hanupata to Wanla', elevation: 3300, desc: 'Into the gorge to Wanla.' },
    { day: 23, title: 'Wanla to Lamayuru via Alchi', elevation: 3800, desc: 'Over Prinkiti La to Lamayuru — end of the trek.' },
    { day: 24, title: 'Monastery day', elevation: 3500, desc: 'Visit Shey, Thiksey and Hemis.' },
    { day: 25, title: 'Leh to Delhi', elevation: 216, desc: 'Flight to Delhi.' }
  ],
  'Manali Peak Expedition': [
    { day: 1, title: 'Arrival in Manali', elevation: 1990, desc: 'Sort climbing gear (boots, crampons, harness); visit Hadimba temple and Vashisht springs.' },
    { day: 2, title: 'Manali to Bakkar Thach', elevation: 3300, desc: 'Drive to Dhundi, walk through forest with views of Hanuman Tibba, Deo Tibba and Indrasan.' },
    { day: 3, title: 'Bakkar Thach to Beas Kund base camp', elevation: 3650, desc: 'A short climb up the ridge to the Beas Kund plateau.' },
    { day: 4, title: 'Acclimatisation day', elevation: 3650, desc: 'Rest and excursion on the Beas Kund plateau.' },
    { day: 5, title: 'Beas Kund to Camp 1', elevation: 4500, desc: 'A 6-7 hour steep uphill with scenic views throughout.' },
    { day: 6, title: 'Camp 1 to Col (Camp 2)', elevation: 5200, desc: 'Technical climbing with full gear to the col.' },
    { day: 7, title: 'Summit attempt — Manali Peak', elevation: 5640, desc: 'Fixed-rope and rock climbing to the summit; panoramic Dhauladhar and Pir Panjal views, then back to Camp 1.' },
    { day: 8, title: 'Camp 1 to Bakkar Thach', elevation: 3300, desc: 'Descend to Bakkar Thach.' },
    { day: 9, title: 'Bakkar Thach to Manali', elevation: 1990, desc: 'Trek to Solang and drive to Manali.' },
    { day: 10, title: 'Extra day for weather', elevation: 0, desc: 'Buffer day.' },
    { day: 11, title: 'Departure from Manali', elevation: 0, desc: 'Depart Manali.' }
  ],
  'Ladakhi Peak Expedition': [
    { day: 1, title: 'Delhi to Manali', elevation: 2050, desc: 'Arrive and visit Hidimba temple.' },
    { day: 2, title: 'Manali', elevation: 2050, desc: 'Acclimatisation walk to old Manali, Goshal and Vashisht; expedition prep.' },
    { day: 3, title: 'Manali to Solang to Dhundi to Bakarthach', elevation: 3300, desc: 'Base of the surrounding peaks — Shetidhar, Ladakhi, Friendship, Manali, Hanuman Tibba.' },
    { day: 4, title: 'Bakarthach to Beas Kund', elevation: 3650, desc: 'Over moraine to the small lake at the source of the Beas.' },
    { day: 5, title: 'Beas Kund — glacier training', elevation: 3650, desc: 'Practice ascending and descending techniques on snow.' },
    { day: 6, title: 'Beas Kund to Camp 1', elevation: 4500, desc: 'A steep ascent to establish Camp 1.' },
    { day: 7, title: 'Camp 1 to Ladakhi Peak and back', elevation: 5536, desc: 'Fixed-rope and rock climbing to the summit, with panoramic Dhauladhar and Pir Panjal views.' },
    { day: 8, title: 'Camp 1 to Bakarthach', elevation: 3300, desc: 'Descend to Beas Kund; evening bonfire celebration.' },
    { day: 9, title: 'Bakarthach to Solang to Manali', elevation: 2050, desc: 'Trek to Solang and drive to Manali.' },
    { day: 10, title: 'Departure from Manali', elevation: 0, desc: 'Transfer for onward journey.' }
  ],
  'Shetidhar Peak Expedition': [
    { day: 1, title: 'Delhi to Manali', elevation: 2050, desc: 'Arrive and visit Hidimba temple.' },
    { day: 2, title: 'Manali', elevation: 2050, desc: 'Acclimatisation walk and expedition prep.' },
    { day: 3, title: 'Manali to Solang to Dhundi to Bakarthach', elevation: 3300, desc: 'Base of the surrounding peaks.' },
    { day: 4, title: 'Bakarthach to Beas Kund', elevation: 3650, desc: 'Over moraine to the source lake of the Beas.' },
    { day: 5, title: 'Beas Kund — glacier training', elevation: 3650, desc: 'Snow ascending and descending practice.' },
    { day: 6, title: 'Beas Kund to Camp 1', elevation: 4500, desc: 'A steep ascent to establish Camp 1.' },
    { day: 7, title: 'Camp 1 to Shetidhar Peak and back to Beas Kund', elevation: 5200, desc: 'A 2am start, roped climb to the summit with panoramic Indrasan and Deo Tibba views.' },
    { day: 8, title: 'Beas Kund to Manali', elevation: 2050, desc: 'Descend to Dhundi and drive to Manali.' },
    { day: 9, title: 'Manali to Delhi', elevation: 216, desc: 'Evening bus to Delhi.' }
  ],
  'Lahaul–Spiti Jeep Safari': [
    { day: 1, title: 'Arrive Delhi', elevation: 216, desc: 'Transfer to hotel, overnight stay.' },
    { day: 2, title: 'Delhi to Manali', elevation: 2050, desc: 'Half-day Delhi tour, evening Volvo coach.' },
    { day: 3, title: 'Manali', elevation: 2050, desc: 'Relax and explore.' },
    { day: 4, title: 'Manali to Chatru', elevation: 3360, desc: 'Over Rohtang into Lahaul; camp on the banks of the Chandra river.' },
    { day: 5, title: 'Chatru to Kaza via Kunzum La', elevation: 4558, desc: 'Cross Kunzum La into Spiti.' },
    { day: 6, title: 'Kaza', elevation: 3650, desc: 'Ki monastery, Kibber village and the Chao Chao Kang Nilda viewpoint.' },
    { day: 7, title: 'Kaza — Dhankar, Tabo, Ki', elevation: 3650, desc: 'Tabo monastery, "the Ajanta of the Himalayas", over a thousand years old.' },
    { day: 8, title: 'Kaza to Chandratal', elevation: 4300, desc: 'Camp by the crescent lake.' },
    { day: 9, title: 'Chandratal to Keylong', elevation: 3080, desc: 'Through Lahaul villages; hike to Khardong monastery.' },
    { day: 10, title: 'Keylong to Udaipur', elevation: 2650, desc: 'Explore Udaipur village and the Mrikula Devi temple.' },
    { day: 11, title: 'Udaipur to Manali via Rohtang Pass', elevation: 3980, desc: 'Return to Manali.' },
    { day: 12, title: 'Manali to Delhi', elevation: 2050, desc: 'Evening Volvo coach.' },
    { day: 13, title: 'Delhi departure', elevation: 216, desc: 'Transfer to airport.' }
  ],
  'Ladakh Monastery Jeep Safari': [
    { day: 1, title: 'Arrive Delhi', elevation: 216, desc: 'Transfer to hotel.' },
    { day: 2, title: 'Delhi to Leh', elevation: 3500, desc: 'Flight to Leh, rest and acclimatise.' },
    { day: 3, title: 'Leh — Shey, Thiksey, Hemis', elevation: 3500, desc: 'Three of Ladakh\'s most important monasteries.' },
    { day: 4, title: 'Leh to Alchi', elevation: 3100, desc: 'Basgo Palace and the 18th-century Likir monastery en route.' },
    { day: 5, title: 'Alchi to Lamayuru', elevation: 3510, desc: 'The dramatic "moonland" monastery on its high promontory.' },
    { day: 6, title: 'Lamayuru to Kargil', elevation: 2700, desc: 'Morning religious ceremony at Lamayuru, then drive to Kargil.' },
    { day: 7, title: 'Kargil to Rangdum', elevation: 3900, desc: 'Up the Suru valley past the twin peaks of Nun and Kun.' },
    { day: 8, title: 'Rangdum to Padum', elevation: 3600, desc: 'Rangdum monastery, then on to the capital of Zanskar.' },
    { day: 9, title: 'Padum', elevation: 3600, desc: 'Karsha, Sani, Thongde, Zangla and Bardan monasteries.' },
    { day: 10, title: 'Padum', elevation: 3600, desc: 'Continued exploration of Zanskar\'s villages and gompas.' },
    { day: 11, title: 'Padum to Rangdum', elevation: 3900, desc: 'Camp at Rangdum.' },
    { day: 12, title: 'Rangdum to Kargil', elevation: 2700, desc: 'Return to Kargil; explore the Turkish-style old town.' },
    { day: 13, title: 'Kargil to Leh', elevation: 3500, desc: 'Basgo monastery en route.' },
    { day: 14, title: 'Leh', elevation: 3500, desc: 'Leisure or further monasteries.' },
    { day: 15, title: 'Leh to Delhi', elevation: 216, desc: 'Flight to Delhi.' }
  ],
  'Ladakh Lakes Jeep Safari': [
    { day: 1, title: 'Delhi arrival', elevation: 216, desc: 'Transfer to hotel.' },
    { day: 2, title: 'Delhi to Leh', elevation: 3500, desc: 'Flight to Leh; Thiksey, Shey and Hemis monasteries.' },
    { day: 3, title: 'Leh — Shey, Thiksey, Hemis', elevation: 3500, desc: 'The great monasteries around Leh.' },
    { day: 4, title: 'Leh local sightseeing', elevation: 3500, desc: 'Leh Palace, Jama Masjid, Spituk and Phyang gompas.' },
    { day: 5, title: 'Leh to Tsokar to Tsomoriri', elevation: 4500, desc: 'Over Tanglang La and the Moore Plains of the Changthang plateau to Karzok.' },
    { day: 6, title: 'Rest day at Tsomoriri', elevation: 4500, desc: 'Kyang, snow fox and bar-headed geese around the lake.' },
    { day: 7, title: 'Tsomoriri to Pangong', elevation: 4300, desc: 'Over Chang La to the vast Pangong Lake.' },
    { day: 8, title: 'Pangong to Leh', elevation: 3500, desc: 'Return to Leh.' },
    { day: 9, title: 'Leh to Khardung La and back', elevation: 5606, desc: 'The world\'s highest motorable pass.' },
    { day: 10, title: 'Leh to Delhi', elevation: 216, desc: 'Early flight to Delhi.' }
  ],
  'Nubra Valley Jeep Safari': [
    { day: 1, title: 'Arrive Delhi', elevation: 216, desc: 'Transfer to hotel.' },
    { day: 2, title: 'Delhi to Leh', elevation: 3500, desc: 'Flight to Leh, acclimatisation day.' },
    { day: 3, title: 'Leh — Shey, Thiksey, Hemis', elevation: 3500, desc: 'The great monasteries around Leh.' },
    { day: 4, title: 'Leh to Panamik', elevation: 3200, desc: 'Over Khardung La into Nubra; camp at Panamik.' },
    { day: 5, title: 'Panamik to Ansa to Panamik', elevation: 3200, desc: 'Ansa monastery and the Panamik hot springs.' },
    { day: 6, title: 'Panamik to Diskit', elevation: 3100, desc: 'Samstanling and Sumur monasteries en route.' },
    { day: 7, title: 'Diskit to Hunder to Diskit', elevation: 3100, desc: 'Hunder monastery and the sand dunes of Nubra.' },
    { day: 8, title: 'Diskit to Leh', elevation: 3500, desc: 'Return over Khardung La.' },
    { day: 9, title: 'Leh', elevation: 3500, desc: 'Phyang, Spituk and the Stok museum.' },
    { day: 10, title: 'Leh to Delhi', elevation: 216, desc: 'Flight to Delhi.' },
    { day: 11, title: 'Depart Delhi', elevation: 216, desc: 'Transfer to airport.' }
  ],
  'Trans-Himalayan Jeep Safari': [
    { day: 1, title: 'Delhi to Shimla', elevation: 2200, desc: 'Drive to Shimla; evening on the Mall Road.' },
    { day: 2, title: 'Shimla', elevation: 2200, desc: 'Indian Institute of Advanced Studies and the Jakho temple.' },
    { day: 3, title: 'Shimla to Sarahan', elevation: 2125, desc: 'Rampur palace en route; the centuries-old Bhimakali temple.' },
    { day: 4, title: 'Sarahan to Sangla', elevation: 2680, desc: 'Along the Hindustan-Tibet road above the Sutlej.' },
    { day: 5, title: 'Sangla to Kalpa', elevation: 2759, desc: 'Kamru village and fort; Kinner Kailash views.' },
    { day: 6, title: 'Kalpa to Tabo', elevation: 3280, desc: 'Via Nako village on its lake; the thousand-year-old Tabo monastery.' },
    { day: 7, title: 'Tabo to Kaza', elevation: 3650, desc: 'Lalung and Dhankar gompas en route.' },
    { day: 8, title: 'Kaza', elevation: 3650, desc: 'Ki monastery and Kibber, one of the world\'s highest villages.' },
    { day: 9, title: 'Kaza to Keylong via Kunzum Pass', elevation: 4558, desc: 'Fine views of the CB ranges from the pass.' },
    { day: 10, title: 'Keylong to Sarchu via Baralacha La', elevation: 4800, desc: 'Camp at Sarchu.' },
    { day: 11, title: 'Sarchu to Leh', elevation: 5359, desc: 'Over Tanglang La onto the high Tibetan plateau; three days to explore Leh.' },
    { day: 12, title: 'Leh to Khardung La and back', elevation: 5600, desc: 'The world\'s highest motorable road.' },
    { day: 13, title: 'Leh to Delhi', elevation: 216, desc: 'Flight to Delhi.' }
  ],
  'Spiti Valley Motorbike Tour': [
    { day: 1, title: 'Manali', elevation: 2000, desc: 'Airport welcome, meet the team, local sightseeing.' },
    { day: 2, title: 'Manali', elevation: 2000, desc: 'Royal Enfield briefing; Solang, Naggar Castle, Roerich museum and Vashisht springs.' },
    { day: 3, title: 'Manali to Banjar Valley (Soja)', elevation: 2683, desc: 'Via Bhuntar and the Manikaran hot springs to the Banjar valley.' },
    { day: 4, title: 'Banjar to Sarahan via Jalori Pass', elevation: 3134, desc: 'Over Jalori Pass; the 800-year-old Bhimakali temple.' },
    { day: 5, title: 'Sarahan to Kalpa', elevation: 3300, desc: 'Temples and views over the Kinner Kailash range.' },
    { day: 6, title: 'Kalpa to Nako', elevation: 3663, desc: 'The lakeside village of Nako in Kinnaur.' },
    { day: 7, title: 'Nako to Kaza', elevation: 3700, desc: 'The ancient Dhankar monastery en route; Key monastery and Kibber nearby.' },
    { day: 8, title: 'Kaza to Chatru', elevation: 4300, desc: 'A day ride to Chandratal Lake, then on to camp at Chatru.' },
    { day: 9, title: 'Chatru to Keylong', elevation: 3080, desc: 'A hotel overlooking the valley.' },
    { day: 10, title: 'Keylong to Manali', elevation: 3980, desc: 'Over Rohtang; farewell dinner.' }
  ],
  'Manali–Leh Ladakh Motorbike Tour': [
    { day: 1, title: 'Manali', elevation: 2000, desc: 'Airport welcome, meet the team, local sightseeing.' },
    { day: 2, title: 'Manali to Keylong via Rohtang', elevation: 3350, desc: '115km over Rohtang Jot to become familiar with the bike and the roads.' },
    { day: 3, title: 'Keylong to Sarchu via Baralacha La', elevation: 4000, desc: 'Over the Baralacha La; a night camping under the stars.' },
    { day: 4, title: 'Sarchu to Leh', elevation: 5359, desc: 'Over Nakee La, Lachulung La and Tanglang La — a long high-altitude ride.' },
    { day: 5, title: 'Leh — sightseeing & Alchi', elevation: 3500, desc: 'Arrange the Nubra permit; ride to the oldest monastery in Ladakh, Alchi.' },
    { day: 6, title: 'Leh to Nubra via Khardung La', elevation: 5540, desc: 'Over the world\'s highest motorable pass into Nubra; camp two nights.' },
    { day: 7, title: 'Nubra Valley', elevation: 3200, desc: 'Camel safari at Hunder and the Panamik hot springs.' },
    { day: 8, title: 'Nubra to Leh', elevation: 3500, desc: 'Return over Khardung La.' },
    { day: 9, title: 'Leh to Pangong Lake via Chang La', elevation: 4300, desc: 'To the vast, part-Tibetan Pangong Lake; camp on its banks.' },
    { day: 10, title: 'Pangong to Leh', elevation: 3500, desc: 'Return to Leh; final markets and shopping.' }
  ],
  'Leh–Ladakh Mountain Biking': [
    { day: 1, title: 'Fly to Delhi; on to Manali', elevation: 2000, desc: 'Train to Chandigarh, bus to Manali; bikes and luggage by vehicle.' },
    { day: 2, title: 'Arrive Manali', elevation: 2000, desc: 'Unpack gear, settle in and rest.' },
    { day: 3, title: 'Manali', elevation: 2000, desc: 'Assemble and check the bikes.' },
    { day: 4, title: 'Ride to Marhi via Rohtang La', elevation: 3978, desc: 'The first riding day, camping at Marhi.' },
    { day: 5, title: 'Ride to near Koksar', elevation: 3140, desc: 'Camp near Koksar.' },
    { day: 6, title: 'Ride to near Jispa via Keylong', elevation: 3142, desc: 'Camp near Jispa.' },
    { day: 7, title: 'Ride to near Patseo', elevation: 3800, desc: 'Camp before Baralacha La.' },
    { day: 8, title: 'Ride to near Sarchu via Baralacha La', elevation: 4883, desc: 'Over the Baralacha La.' },
    { day: 9, title: 'Ride to near Pang via Lachlung La', elevation: 5065, desc: 'Over the Lachlung La.' },
    { day: 10, title: 'Ride around Pang', elevation: 4885, desc: 'Acclimatisation riding.' },
    { day: 11, title: 'Ride to the More Plains', elevation: 4700, desc: 'Camp on the high plateau.' },
    { day: 12, title: 'Ride to near Tanglang La', elevation: 5328, desc: 'Toward the second-highest motorable pass.' },
    { day: 13, title: 'Ride to near Upshi', elevation: 3400, desc: 'Descend toward the Indus.' },
    { day: 14, title: 'Ride to Stok village', elevation: 3523, desc: 'To the Stok Highland hotel near Leh.' },
    { day: 15, title: 'Indus valley tours / flex day', elevation: 3500, desc: 'Rides or rest in the Indus valley.' },
    { day: 16, title: 'Ride to Khardung La and back', elevation: 5606, desc: 'The world\'s highest motorable pass, then pack in Stok.' },
    { day: 17, title: 'Fly Leh to Delhi', elevation: 216, desc: 'Transfer to Delhi.' }
  ],
  'Spiti Valley Cycling Tour': [
    { day: 1, title: 'Arrival Delhi', elevation: 216, desc: 'Hotel.' },
    { day: 2, title: 'Delhi to Chandigarh to Mandi', elevation: 760, desc: 'Drive toward the hills.' },
    { day: 3, title: 'Mandi to Manali', elevation: 2000, desc: '125km drive.' },
    { day: 4, title: 'Bike Manali to Marhi', elevation: 3360, desc: '35km climb.' },
    { day: 5, title: 'Bike Marhi to Dadar Pul', elevation: 3250, desc: '42km, camp.' },
    { day: 6, title: 'Bike Dadar Pul to Takcha', elevation: 3600, desc: '54km, camp.' },
    { day: 7, title: 'Bike Takcha to Ki', elevation: 4116, desc: '68km; the Ki monastery.' },
    { day: 8, title: 'Bike Ki to Komik', elevation: 4500, desc: '35km to one of the world\'s highest villages.' },
    { day: 9, title: 'Bike Langcha to Tabo', elevation: 3280, desc: '45km; the Tabo monastery.' },
    { day: 10, title: 'Bike Tabo to Nako', elevation: 3663, desc: '64km to the lakeside village.' },
    { day: 11, title: 'Bike Nako to Jangi', elevation: 2800, desc: '71km.' },
    { day: 12, title: 'Bike Jangi to Sangla', elevation: 2680, desc: '62km into the Sangla valley.' },
    { day: 13, title: 'Bike Sangla to Shimla', elevation: 2200, desc: '25km ride and 200km drive.' },
    { day: 14, title: 'Drive Shimla to Delhi', elevation: 216, desc: 'By bus and train.' },
    { day: 15, title: 'Transfer to airport', elevation: 216, desc: 'Onward flight.' }
  ],
  'Adventure Camp': [
    { day: 1, title: 'Delhi to Manali to Jagatsukh', elevation: 2000, desc: 'Drive to the heritage village of Jagatsukh; Gaytri Devi and old Shiva temples.' },
    { day: 2, title: 'Rock climbing and rappelling', elevation: 2000, desc: 'A day on the crags, with an optional afternoon trek.' },
    { day: 3, title: 'AD tunnel point to Chikka', elevation: 3350, desc: 'Trek in with an evening river-crossing session; overnight tents.' },
    { day: 4, title: 'Chikka to Seri', elevation: 3800, desc: 'A gradual ascent to the scenic Seri campsite.' },
    { day: 5, title: 'Seri to Chandertaal and back', elevation: 4300, desc: 'To the source lake below Deo Tibba, then back to camp.' },
    { day: 6, title: 'Seri to Chikka', elevation: 3350, desc: 'An easy return with beautiful views.' },
    { day: 7, title: 'Chikka to Manali', elevation: 2000, desc: 'Through pine forest with bird\'s-eye views of the Beas valley.' }
  ],
  'Skill Development Camp': [
    { day: 1, title: 'Arrive Manali', elevation: 2000, desc: 'Check into Camp Manali.' },
    { day: 2, title: 'Trek to Jogini Falls', elevation: 2400, desc: 'To Jogini Falls / Khanyal village and back by evening.' },
    { day: 3, title: 'Rock craft on the Beas', elevation: 2000, desc: 'Rock climbing, rappelling and river crossing.' },
    { day: 4, title: 'Snow hiking', elevation: 3000, desc: 'A long hike on snow with packed lunch.' },
    { day: 5, title: 'Solang activities', elevation: 2500, desc: 'Paragliding, zorbing and a short trek at Solang.' },
    { day: 6, title: 'River rafting on the Beas', elevation: 1900, desc: 'White-water rafting.' },
    { day: 7, title: 'Depart Manali', elevation: 2000, desc: 'Depart after breakfast.' }
  ]
};

/* Node interop for the generator — must be last */
if (typeof module !== 'undefined' && module.exports) {
  module.exports = { MH_ROUTES, MH_ITINERARIES };
}
